### ISSUE TITLE
Wrong Page title when opening up own post

### ISSUE THREAD

**Issue by mightypanda-x** [BoomApps-LLC/SteemApp-Android#14]
#### Expected Behavior
Page title should be BLOG when you open your own post.

#### Actual Behavior
Page title is displayed as FEED when you open your own post.

#### Steps to Reproduce
- Login into the app.
- Go to BLOG page.
- Click on one of your blogs.
- Check Page title, it is displayed as FEED.

![SmartSelect_20180630-004622_SteemApp.jpg](https://ipfs.busy.org/ipfs/QmaDZEsTsPD5CKyiFzyDNavxTjPY2LyPr7D8uqUoAxnmwb)
![image.png](https://ipfs.busy.org/ipfs/QmSGRoWUYLEA8cRK6nmTM85bWukt5BAqFscHmUNqE2DwsT)

Device : Samsung S8
System Operating : 8.0.0 Oreo
Browser : Google Chrome ( 66.0.3359.158 Version)
App Version: 2.0.3 beta

**Comment by BoomAppsLLC** [comment]
I see. Thanks, @mightypanda-x. We will fix it.

**Comment by BoomAppsLLC** [comment]
Created pull request: #28
