### ISSUE TITLE
Up voting a post shows inconsistent vote count on BLOG list and Post details

### ISSUE THREAD

**Issue by mightypanda-x** [BoomApps-LLC/SteemApp-Android#15]
#### Expected Behavior
Post should show same number of up-votes on both Blog list and Post details

#### Actual Behavior
Up voting a post shows inconsistent vote count on BLOG list and Post details.

#### Steps to Reproduce
- Create a new post on the new SteemApp Beta version with Upvote own post turned off.
- Open the post by clicking on the post tile in the BLOG list.
- Up-vote your post from inside the post.
- Go back to BLOG list and refresh. 
- Post still shows 0 count but going inside the post shows either 1 or 2 votes.

**Only 1 vote was cast on the post**
![image.png](https://ipfs.busy.org/ipfs/QmUusbimNwJexyhNcKm953rnDaujctcZsVvMpipSMT8DTh)

#### Possible Solution
Use the same Source of truth for storing the number of votes against a post.

#### Recording of the issue
https://youtu.be/NBTT64UW4oU

Device : Samsung S8
System Operating : 8.0.0 Oreo
Browser : Google Chrome ( 66.0.3359.158 Version)
App Version: 2.0.3 beta

**Comment by tobias-g1** [comment]
I was able to replicate this issue, interestingly this issue doesn't seem to occur on my main account which has 2400 SP with 17% vote and was able to replicate on another account with < 5 (the vote was cast successfully) with 100%. The following explains this further:

When I tested on this post:

https://steemit.com/abc/@votezilla/abc

I was able to replicate the issue, however when I tested on this post:

https://steemit.com/test/@tobias-g/steem-app-testing

It worked as expected.

**Comment by brazer** [comment]
Thank you, @tobias-g1. We will check it.

**Comment by VitalyGrechikha** [comment]
Hi @mightypanda-x 
Thank you, for your report. We used "net_votes" field from the response, but it doesn't consistent with actual voters count.
So, we changed it and now the app takes a voters number from "active_votes" array with some rules
