### ISSUE TITLE
[ steempApp v 2.0.3 ] Upvote And reblog button automatically Opens The Post Instead Of Upvoting & Rebloging it

### ISSUE THREAD

**Issue by realrufans** [BoomApps-LLC/SteemApp-Android#16]
#### Expected behavior
The upvote and reblog button shown before opening a post ought to upvote or reblog a post respectively.

#### Actual behavior
Upvote and reblog button opens a post when trying to upvote or reblog. And when the post is opened, the reblog button isn't clickable.

#### How to reproduce

* download the app [Steemapp](https://play.google.com/store/apps/details?id=com.boomapps.steemapp)
* sign in and click on feeds
* try upvoting  or rebloging a post ( without opening the Post)

<Hr>

* Browser/App version: steemapp version 2.0.3
* Operating system: android  8.0 Oreo.  Tecno camon X pro

#### Recording Of The Bug
https://youtu.be/FxHNuDr8qDU

**Comment by brazer** [comment]
I see. Thanks. We will fix it later.

**Comment by VitalyGrechikha** [comment]
Hi @realrufans 
It is not an issue - this functionality will implement later. Sorry
