### ISSUE TITLE
SteemApp Beta [v2.0.3] & SteemApp Stable [v1.0.3] login bug

### ISSUE THREAD

**Issue by kr-nahid** [BoomApps-LLC/SteemApp-Android#20]
How to Reproduce:
* install the SteemApp Beta 2.0.3
* Then open the app and enter any username you want to enter(In this case I'm using my 2nd account to reproduce this bug, because this is a big security issue of this app and any account can be targeted.)
* After entering any username use your own post key by QR code or input private posting key .
* Then click login.
* Note that the user will be able to enter into the username account after log in by your post key but any username)
* Note that this security issue is the same for SteemApp Stable v1.0.3
Note: This is a very sensitive security issue bug. So I urge to the PO to resolve this issue as fast as possible.

#### Recording Of The Bug
https://www.youtube.com/watch?v=8DODadnopAU&feature=youtu.be

**Comment by tobias-g1** [comment]
There is no security concern here, you cannot post on behalf of another user it will invalidate the request as the private posting key will be incorrect. I don't actually believe this is a bug, I wouldn't be 100% this is a bug as they've built the functionality into the application to redirect in the event a users posts.

**Comment by kr-nahid** [comment]
login with any username use your own post key by QR code or input private posting key isn't it bug sir ?

**Comment by realrufans** [comment]
That's true, I can't post on behalf of  another user.

**Comment by VitalyGrechikha** [comment]
Hi @kr-nahid 
@tobias-g1 is right, you can log in without POST key or with key - it doesn't matter 
look:
1) the app doesn't check your POST key; the app only save it in the special system keystore (in encrypted form)
2) key is used only when you post your story or vote - the app gets it from keystore and send it as a parameter in the request to the server
3) if you sign out all data connected to the app in keystore will be cleared
