### ISSUE TITLE
Tags should not allow special characters

### ISSUE THREAD

**Issue by mightypanda-x** [BoomApps-LLC/SteemApp-Android#26]
#### Expected Behavior
User should not be able to add any special characters (except for -) in the tags .

#### Actual Behavior
User can add special characters in the tags as long as they are not in first tag. This creates a broken/invalid tag on the post after posting.

#### Steps to Reproduce
- Click create post.
- Enter title and click Next.
- Enter story text and click Next.
- Enter first tag in alphabet and numbers.
- Enter second tag with special characters like !@#$
- Post.

#### Recording of the issue
https://youtu.be/J7Fh3JUaJaE

#### Post with the issue
https://steemit.com/test/@fastandcurious/test-post-for-special-characters

Device : Samsung S8
System Operating : 8.0.0 Oreo
Browser : Google Chrome ( 66.0.3359.158 Version)
App Version: 2.0.3 beta

**Comment by BoomAppsLLC** [comment]
@mightypanda-x, thanks for reporting. We will fix it.

**Comment by VitalyGrechikha** [comment]
I have added  input chars filtering - user can input all chars and digits and chars "_" and "-" from 2nd position
