### ISSUE TITLE
Uploading an image from the library will take the user to the wallet

### ISSUE THREAD

**Issue by shaphir** [BoomApps-LLC/SteemApp-Android#3]
#### Expected behavior
When I select one of the images from the library, the image should be uploaded.

#### Actual behavior
Uploading an image from the library will take the user to the wallet and the image is not uploaded

#### How to reproduce
* Open the app
* Presing create post
* In the story, you hit upload picture button and select ```choose from library```
after selecting the image and uploading it, it will take me to the wallet

* App version: 1.0.3
* Operating system: Oppo A57 android version 6.0.1

#### Recording Of The Bug
https://youtu.be/QFPG1r1BSUY

**Comment by BoomAppsLLC** [comment]
Thank you for bug reporting! We will fix it later.

**Comment by shaphir** [comment]
Sorry it's mistake,  App version is a 2.0.3

**Comment by BoomAppsLLC** [comment]
Created pull request: #24
