### ISSUE TITLE
SteemApp v2.1.1 cashes while uploading and image. 

### ISSUE THREAD

**Issue by ashiqurakash** [BoomApps-LLC/SteemApp-Android#33]
How to reproduce:
* To reproduce this bug fresh start SteemApp v2.1.1 and login.
* At the bottom middle you'll find "post create" option click on that.
* Then type any title on the title box and click "next" at the top right of the app.
* After clicking on "next" app will take you to the description box. And you'll see a tool tray at the bottom of the app. Simply just swipe left and you'll find a "image" icon at the very right of the tray.
* Click on the image icon and the you will find two options chose any of that. For example click on "chose from library" just like the video I've recorded. And after that chose a photo.
* Note that after choosing a photo from the library it will start to upload and while uploading app stops working.

Recorded video:https://vimeo.com/282544043

**Comment by VitalyGrechikha** [comment]
duplicate #38 
#38 was fixed
