### ISSUE TITLE
Doesn't show profile after typing title in landscape mode. 

### ISSUE THREAD

**Issue by ashiqurakash** [BoomApps-LLC/SteemApp-Android#4]
How to reproduce
1. Fresh start SteemApp
2. At the bottom right you will find profile click on it. 
3. Then click on the create post at the bottom middle of the app.
4. Then type a title in landscape mode and you will find a "NEXT" button at the right of the text box while you are typing in landscape mode.
5. Click on the "NEXT" button several times just like the video I've provided.
6. Note that the "NEXT" button won't work then click on back button of your android phone twice to come back to profile from where you've started to create post. 
7. Note that after click on the back button of the user's android phone twice to come back to profile the app is only showing wallet while at the bottom right it's clearly marked the profile section. 

Version: SteemApp v1.0.3
Platform : Android 7.0

Recorded video: https://vimeo.com/277705102

**Comment by tobias-g1** [comment]
As you now only support portrait in 2.0.3 I believe this is resolved.

**Comment by BoomAppsLLC** [comment]
This issue is not reproduced in new 2.0.3 version. Thank you for bug reporting.
