### ISSUE TITLE
Next button should stay disabled if no story is entered

### ISSUE THREAD

**Issue by mightypanda-x** [BoomApps-LLC/SteemApp-Android#6]
#### Expected Behavior
User should not be able to go to the Tags page without entering Post Story.

#### Actual Behavior
User can get to the Tags screen without entering anything in story.

#### Steps to Reproduce
- Click on create post link in the bottom(Installation [Link](https://play.google.com/store/apps/details?id=com.boomapps.steemapp)) 
- Enter title and click next.
- On the Story page, click left Arrow to go back to title page.
- Click again on the Next button on Title page.
- After landing on Story screen again, you will notice that Next button is enabled and clicking on it takes you to Add Tags without asking for a story.

#### Recording of the issue
https://www.youtube.com/watch?v=Yi5T_Yoer7U&feature=youtu.be

Device : Samsung S8
System Operating : 8.0.0 Oreo
Browser : Google Chrome ( 66.0.3359.158 Version)
App Version: 2.0.3 beta

**Comment by BoomAppsLLC** [comment]
Thank you for bug reporting. We will fix it.

**Comment by BoomAppsLLC** [comment]
Pull request was created: #25
